### ISSUE TITLE
missing source/admin directory

### ISSUE THREAD

**Issue by homerhanumat** [cfjedimaster/Static-Sites-Book#1]
I am reading the pre-release of the book and trying out the hexocms project.  The text mentions a source/admin/index.ejs file, but I do not find a source/admin directory.

**Comment by remotesynth** [comment]
Thanks. I just committed a new copy of the zip that should contain the admin template. Let me know if it works out for you.

**Comment by homerhanumat** [comment]
It worked:  I am able to log on to the CMS and see the posts.  Thanks!
